---
# Not needed since ansible already has them
#  command: hostname
#  register: hostname

- name: "install required packages for grafana"
  yum:
    name: 
      - openssl
      - grafana
      - mariadb
      - mariadb-server-utils
    state: latest
  become: True
  register: installed

- name: set mariadb script file
  copy:
    src: "files/mariadb.build"
    dest: "/mariadb.build"
  register: mariadb_dump

- name: "start mariadb service"
  service:
    name: mariadb
    state: started
    enabled: yes

- name: generate mariadb
  shell: "mysql < /mariadb.build"
  when: mariadb_dump.changed

- name: "set grafana config file"
  copy:
    src: "files/grafana.ini"
    dest: "/etc/grafana/grafana.ini"

- name: "include grafana datasources"
  copy:
    src: "files/grafanadb.yml"
    dest: "/etc/grafana/provisioning/datasources/"

- name: "create dir for json models"
  file:
    path: "/etc/grafana/jsonmodels"
    state: directory

- name: "include grafana dashboard models"
  copy:
    src: "files/cpu_metrics.json"
    dest: "/etc/grafana/jsonmodels/cpu_metrics.json"


- name: "include grafana dashboard configs"
  copy:
    src: "files/cpu_metrics.yml"
    dest: "/etc/grafana/provisioning/dashboards/cpu_metrics.yml"

- name: "start grafana service"
  service:
    name: grafana-server
    state: started
    enabled: yes

      #
