{
 "title": "XRootD Servers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "XRootD uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time()-xrd_tos", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Instance Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "targets": [
    { "expr": "xrd_config_info" }
   ]
  },
  {
   "title": "Data in ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    { "expr": "rate(xrd_link_in[1m])" }
   ]
  },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    { "expr": "xrd_oss_paths_0_free" }
   ]
  },
  {
   "title": "Data out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    { "expr": "rate(xrd_link_out[60s])" }
   ]
  },
  {
   "title": "Free Inodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "xrd_oss_paths_0_ifr" }
   ]
  }
 ]
}