---

- name: Install python
  yum:
    name: python39

- name: create links
  file:
    src: "/usr/bin/{{ item }}3"
    dest: "/usr/bin/{{item}}"
    state: link
  loop:
    - pip
    - python

- name: copy exporter.py
  copy:
    src: files/xrootd-exporter.py
    dest: /usr/bin/
    mode: 775

- name: install python dependencies
  pip: 
    name: prometheus_client

- name: copy exporter unit file
  copy:
    src: files/xrootd-exporter@.service
    dest: /usr/lib/systemd/system/
    mode: 771
    owner: xrootd

- name: enable and start xrootd-exporter
  service:
    name: xrootd-exporter@1
    state: started
    enabled: yes
