---
# Not needed since ansible already has them
#  command: hostname
#  register: hostname

- name: "install required packages for xrootd"
  yum:
    name: 
      - git
      - gcc
      - cmake
      - zlib
      - zlib-devel
      - uuid
      - libuuid-devel
      - json-c-devel
      - json-c
      - systemd-devel
      - tinyxml
      - openssl
      - openssl-devel
    state: latest
  become: True

- name: "get xrootd version from git"
  git: 
    repo: "https://github.com/xrootd/xrootd/"
    dest: /xrootd-git
    version: v5.5.1
  register: git

- name: "create xrootd build dir"
  file:
    path: "/xrootd-build"
    state: directory
  become: True

- name: "cmake xrootd" 
  ansible.builtin.command: "{{ item }}"
  loop:
    - "cmake /xrootd-git -Wno-dev" 
    - "make install -j2"
  args:
    chdir: /xrootd-build
  when: git.changed
  become: True
